# Generated by Django 4.1.6 on 2023-02-16 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
