# Generated by Django 4.1.6 on 2023-02-16 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
